# Generated by Django 4.2.23 on 2025-07-01 19:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionItem',
            fields=[
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tasks.task',),
        ),
        migrations.AddField(
            model_name='task',
            name='auto_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='posted_to_monday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='source_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RawTranscript',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255, unique=True)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='tasks.meeting')),
            ],
            options={
                'verbose_name': 'Raw transcript',
                'verbose_name_plural': 'Raw transcripts',
                'ordering': ['-created_at'],
            },
        ),
    ]
