# Generated by Django 4.2.23 on 2025-07-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_securityquestion_id_alter_task_expires_after_h_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-meeting__date', '-created_at']},
        ),
        migrations.AddField(
            model_name='meeting',
            name='execution_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
